# Generated by Django 2.2.27 on 2026-06-13 09:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_init_basemaps'),
        ('changedetect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField(help_text="Index of the feature inside the result's GeoJSON FeatureCollection (sorted by area, descending).")),
                ('label', models.CharField(help_text='One of ALLOWED_LABELS in ai_classify.py.', max_length=32)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0-1.0 confidence reported by the classifier.')),
                ('source', models.CharField(default='llm_fallback', help_text='geodeep_aerovision / geodeep_cars / llm_fallback', max_length=32)),
                ('rationale', models.TextField(blank=True, default='', help_text='Short human-readable Chinese reason from the model.')),
                ('centroid', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="[lng, lat] of the feature's geometric centroid.")),
                ('bbox', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="[minx, miny, maxx, maxy] of the feature's bbox.")),
                ('area_m2', models.FloatField(default=0.0, help_text='Area in m² (denormalised so the API can list without re-reading GeoJSON).')),
                ('model', models.CharField(default='', help_text="Model id used (e.g. 'aerovision' or 'MiniMax-M3').", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['result_id', 'feature_index'],
            },
        ),
        migrations.CreateModel(
            name='ChangeInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('analyze', '变化原因解读'), ('summary', '报告摘要')], default='analyze', max_length=16)),
                ('text', models.TextField(help_text='LLM-generated Chinese text.')),
                ('model', models.CharField(default='', help_text='Model id that produced this insight (MiniMax-M3 by default).', max_length=64)),
                ('usage', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Token usage stats from the LLM response.')),
                ('elapsed_ms', models.IntegerField(default=0, help_text='Round-trip time to the LLM gateway.')),
                ('error', models.TextField(blank=True, default='', help_text='If the LLM call failed, the error string. Otherwise empty.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pair_id', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='PairRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = best, 2 = next, etc.')),
                ('task_a_id', models.CharField(help_text='Task id (UUID string) of the earlier task.', max_length=64)),
                ('task_b_id', models.CharField(help_text='Task id of the later task.', max_length=64)),
                ('reason', models.TextField(blank=True, default='', help_text='1-2 sentence Chinese justification from the LLM.')),
                ('model', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_id', 'rank'],
            },
        ),
        migrations.RemoveIndex(
            model_name='changepair',
            name='changedetect_cp_proj_idx',
        ),
        migrations.RemoveIndex(
            model_name='changepair',
            name='changedetect_cp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeresult',
            name='changedetect_cr_pair_idx',
        ),
        migrations.AlterField(
            model_name='changepair',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task id, used by frontend for progress polling.', max_length=64),
        ),
        migrations.AlterField(
            model_name='changepair',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='User-tweakable thresholds: pixel_threshold, dsm_min_h, min_area_m2, enable_pixel, enable_dsm, crop_geojson (optional).'),
        ),
        migrations.AlterField(
            model_name='changeresult',
            name='geojson_path',
            field=models.CharField(help_text='Absolute path to the GeoJSON file with change polygons.', max_length=512),
        ),
        migrations.AlterField(
            model_name='changeresult',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Stats: total_area_m2, added_area_m2, removed_area_m2, polygon_count, mean_intensity, etc.'),
        ),
        migrations.AlterField(
            model_name='changeresult',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', help_text='Optional PNG heatmap, served as a static asset.', max_length=512),
        ),
        migrations.AddIndex(
            model_name='changepair',
            index=models.Index(fields=['project', '-created_at'], name='changedetec_project_8297dd_idx'),
        ),
        migrations.AddIndex(
            model_name='changepair',
            index=models.Index(fields=['status'], name='changedetec_status_32cd45_idx'),
        ),
        migrations.AddIndex(
            model_name='changeresult',
            index=models.Index(fields=['pair', 'layer_type'], name='changedetec_pair_id_78b41c_idx'),
        ),
        migrations.AddField(
            model_name='pairrecommendation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_recommendations', to='app.Project'),
        ),
        migrations.AddField(
            model_name='changeinsight',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='changedetect.ChangePair'),
        ),
        migrations.AddField(
            model_name='changeannotation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_annotations', to='changedetect.ChangeResult'),
        ),
        migrations.AlterUniqueTogether(
            name='pairrecommendation',
            unique_together={('project', 'rank')},
        ),
        migrations.AddIndex(
            model_name='changeinsight',
            index=models.Index(fields=['pair', 'kind'], name='changedetec_pair_id_2f5088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='changeinsight',
            unique_together={('pair', 'kind')},
        ),
        migrations.AddIndex(
            model_name='changeannotation',
            index=models.Index(fields=['result', 'label'], name='changedetec_result__655810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='changeannotation',
            unique_together={('result', 'feature_index')},
        ),
    ]
