# Generated by Django 2.2.27 on 2026-06-06 08:20
#
# NOTE: This migration was hand-edited. Django 2.2's serializer emitted
# `import coreplugins.flight-planner.models`, which is a SyntaxError because
# of the dash in the package name (the package is importable via
# importlib.import_module, but not via a plain `import` statement).
#
# The fix is to use string-based `default` references — Django resolves
# these with django.utils.module_loading.import_string, which calls
# importlib.import_module internally and handles dash-named packages.

import django.contrib.postgres.fields.jsonb
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightProject',
            fields=[
                ('id', models.CharField(
                    default='coreplugins.flight-planner.models._gen_short_id',
                    editable=False, max_length=12, primary_key=True, serialize=False,
                )),
                ('name', models.CharField(max_length=128)),
                ('drone_model', models.CharField(
                    help_text='DJI model key, e.g. M30, MINI_3, AVATA_2. See drone_models.DRONE_MODELS.',
                    max_length=64,
                )),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='flight_planner_projects',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Flight Project',
                'verbose_name_plural': 'Flight Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightMission',
            fields=[
                ('id', models.CharField(
                    default='coreplugins.flight-planner.models._gen_short_id',
                    editable=False, max_length=12, primary_key=True, serialize=False,
                )),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(
                    choices=[
                        ('polygon', 'Polygon survey'),
                        ('spiral', 'Spiral'),
                        ('orbit', 'Orbit'),
                        ('cable', 'Cable cam'),
                        ('corkscrew', 'Corkscrew'),
                        ('grid', 'Panel grid'),
                    ],
                    max_length=32,
                )),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=dict,
                    help_text="Algorithm + WPML parameters: {'algo': {...}, 'wpml': {...}}",
                )),
                ('waypoints', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=list,
                    help_text='List of waypoint dicts: {lat, lon, alt, speed, gimbal_pitch, ...}',
                )),
                ('bounds', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=list,
                    help_text='[min_lat, min_lon, max_lat, max_lon]',
                )),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=dict,
                    help_text='{waypoints, distance_m, area_m2, duration_s, ...}',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='missions',
                    to='flight_planner.FlightProject',
                )),
            ],
            options={
                'verbose_name': 'Flight Mission',
                'verbose_name_plural': 'Flight Missions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flightmission',
            index=models.Index(fields=['project', '-updated_at'], name='flight_plan_project_85cf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='flightmission',
            index=models.Index(fields=['kind'], name='flight_plan_kind_832385_idx'),
        ),
    ]
