"""
KML exporter for mission waypoints.

Produces a standard KML 2.2 file (no DJI proprietary fields, no Litchi private
schema). Compatible with Google Earth, QGroundControl, Mission Planner, etc.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from typing import List, Optional

from .algorithms import Waypoint


KML_NS = "http://www.opengis.net/kml/2.2"
ET.register_namespace("", KML_NS)


def _coord(w: Waypoint) -> str:
    return f"{w.lon:.8f},{w.lat:.8f},{w.alt:.2f}"


def _extended_data(w: Waypoint) -> ET.Element:
    ed = ET.Element(f"{{{KML_NS}}}ExtendedData")
    fields = [
        ("index", str(w.index)),
        ("altitude_m", f"{w.alt:.2f}"),
        ("speed_mps", f"{w.speed:.2f}"),
        ("gimbal_pitch_deg", str(w.gimbal_pitch)),
        ("heading_deg", "" if w.heading is None else str(w.heading)),
        ("action", w.action),
        ("curve_radius_m", f"{w.curve_radius:.2f}"),
        ("hold_time_s", f"{w.hold_time:.2f}"),
    ]
    for name, value in fields:
        d = ET.SubElement(ed, f"{{{KML_NS}}}Data", {"name": name})
        v = ET.SubElement(d, f"{{{KML_NS}}}value")
        v.text = value
    return ed


def waypoints_to_kml(
    waypoints: List[Waypoint],
    name: str = "Mission",
    description: str = "Generated by WebODM Flight Planner (open source, standard KML 2.2)",
    open_at_start: bool = True,
) -> str:
    """Build a standard KML 2.2 document."""
    kml = ET.Element(f"{{{KML_NS}}}kml")
    doc = ET.SubElement(kml, f"{{{KML_NS}}}Document")
    ET.SubElement(doc, f"{{{KML_NS}}}name").text = name
    ET.SubElement(doc, f"{{{KML_NS}}}description").text = description
    ET.SubElement(doc, f"{{{KML_NS}}}open").text = "1" if open_at_start else "0"

    style = ET.SubElement(doc, f"{{{KML_NS}}}Style", {"id": "flightPath"})
    ls = ET.SubElement(style, f"{{{KML_NS}}}LineStyle")
    ET.SubElement(ls, f"{{{KML_NS}}}color").text = "ff0000ff"  # red (aabbggrr)
    ET.SubElement(ls, f"{{{KML_NS}}}width").text = "3"

    pstyle = ET.SubElement(doc, f"{{{KML_NS}}}Style", {"id": "waypointIcon"})
    icon = ET.SubElement(pstyle, f"{{{KML_NS}}}IconStyle")
    ET.SubElement(icon, f"{{{KML_NS}}}color").text = "ff00ffff"  # yellow
    ET.SubElement(icon, f"{{{KML_NS}}}scale").text = "0.8"
    href = ET.SubElement(icon, f"{{{KML_NS}}}Icon")
    ET.SubElement(href, f"{{{KML_NS}}}href").text = (
        "http://maps.google.com/mapfiles/kml/shapes/track.png"
    )

    placemark = ET.SubElement(doc, f"{{{KML_NS}}}Placemark")
    ET.SubElement(placemark, f"{{{KML_NS}}}name").text = f"{name} - Flight Path"
    ET.SubElement(placemark, f"{{{KML_NS}}}styleUrl").text = "#flightPath"
    ls2 = ET.SubElement(placemark, f"{{{KML_NS}}}LineString")
    ET.SubElement(ls2, f"{{{KML_NS}}}tessellate").text = "0"
    ET.SubElement(ls2, f"{{{KML_NS}}}altitudeMode").text = "relativeToGround"
    coords = ET.SubElement(ls2, f"{{{KML_NS}}}coordinates")
    coords.text = " ".join(_coord(w) for w in waypoints)

    folder = ET.SubElement(doc, f"{{{KML_NS}}}Folder")
    ET.SubElement(folder, f"{{{KML_NS}}}name").text = "Waypoints"
    ET.SubElement(folder, f"{{{KML_NS}}}open").text = "0"

    for w in waypoints:
        pm = ET.SubElement(folder, f"{{{KML_NS}}}Placemark")
        ET.SubElement(pm, f"{{{KML_NS}}}name").text = f"WP {w.index}"
        ET.SubElement(pm, f"{{{KML_NS}}}styleUrl").text = "#waypointIcon"
        pm.append(_extended_data(w))
        pt = ET.SubElement(pm, f"{{{KML_NS}}}Point")
        ET.SubElement(pt, f"{{{KML_NS}}}altitudeMode").text = "relativeToGround"
        c = ET.SubElement(pt, f"{{{KML_NS}}}coordinates")
        c.text = _coord(w)

    ET.indent(kml, space="  ")
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(
        kml, encoding="unicode", xml_declaration=False
    )


def waypoints_to_geojson(waypoints: List[Waypoint], name: str = "Mission") -> str:
    """Build a GeoJSON FeatureCollection."""
    import json
    features = []
    if waypoints:
        features.append({
            "type": "Feature",
            "properties": {"name": f"{name} - flight", "kind": "flight_path"},
            "geometry": {
                "type": "LineString",
                "coordinates": [[w.lon, w.lat, w.alt] for w in waypoints],
            },
        })
        for w in waypoints:
            features.append({
                "type": "Feature",
                "properties": {
                    "name": f"WP {w.index}",
                    "kind": "waypoint",
                    "alt": w.alt,
                    "speed": w.speed,
                    "gimbal_pitch": w.gimbal_pitch,
                    "heading": w.heading,
                    "action": w.action,
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [w.lon, w.lat, w.alt],
                },
            })
    return json.dumps({
        "type": "FeatureCollection",
        "name": name,
        "features": features,
    }, indent=2)
